#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.11f1_38bd7dec5000"
#define UNITY_VERSION_FULL_NICE "2018.2.11f1 (38bd7dec5000)"
#define UNITY_VERSION_BLD 3718525
#define UNITY_VERSION_DATE 1538123524
#define UNITY_VERSION_WIN "2018.2.11.3718525"
#define UNITY_VERSION_BRANCH "2018.2/release"
